package io.github.entewurzelauskuh.mp4tomp3.engine

import android.content.Context
import android.net.Uri
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import io.github.entewurzelauskuh.mp4tomp3.jobs.FailureReason
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import java.io.ByteArrayOutputStream
import java.io.File
import java.util.concurrent.atomic.AtomicInteger

/**
 * Instrumented tests for the real LAME engine (spec §8 Phase 2, §9.3). Requires the fixtures
 * in `androidTest/assets/` (generated by `scripts/make_fixtures.sh`) and an emulator.
 */
@RunWith(AndroidJUnit4::class)
class MediaCodecLameConverterTest {
    private val instrumentation = InstrumentationRegistry.getInstrumentation()

    // The app context (its ContentResolver opens the source); the fixtures live in the TEST
    // APK, so they are read from the instrumentation context's assets, not the app's.
    private val context: Context get() = instrumentation.targetContext
    private val converter = MediaCodecLameConverter()

    private fun assetUri(name: String): Uri {
        val out = File(context.cacheDir, name)
        instrumentation.context.assets.open(name).use { input ->
            out.outputStream().use { input.copyTo(it) }
        }
        return Uri.fromFile(out)
    }

    private fun convert(
        asset: String,
        isCancelled: () -> Boolean = { false },
        onProgress: (Int) -> Unit = {},
    ): Pair<ConverterResult, ByteArray> {
        val sink = ByteArrayOutputStream()
        val result = converter.convert(context, assetUri(asset), sink, onProgress, isCancelled)
        return result to sink.toByteArray()
    }

    private fun isValidMp3(bytes: ByteArray): Boolean {
        if (bytes.size < 4) return false
        val id3 = bytes[0] == 'I'.code.toByte() && bytes[1] == 'D'.code.toByte() && bytes[2] == '3'.code.toByte()
        val frameSync = bytes[0] == 0xFF.toByte() && (bytes[1].toInt() and 0xE0) == 0xE0
        return id3 || frameSync
    }

    @Test
    fun stereoAacConvertsToValidMp3() {
        val progress = mutableListOf<Int>()
        val (result, mp3) = convert("sine_stereo_aac_3s.mp4", onProgress = { progress.add(it) })
        assertEquals(ConverterResult.Success, result)
        assertTrue("output should be a valid MP3", isValidMp3(mp3))
        assertTrue("should produce a non-trivial amount of MP3", mp3.size > 1000)
        assertEquals("progress must be monotonic", progress.sorted(), progress)
        assertEquals("progress must reach 100", 100, progress.last())
    }

    @Test
    fun monoAacConvertsToValidMp3() {
        val (result, mp3) = convert("sine_mono_aac_3s.mp4")
        assertEquals(ConverterResult.Success, result)
        assertTrue(isValidMp3(mp3))
    }

    @Test
    fun videoWithoutAudioFailsWithNoAudioTrack() {
        val (result, _) = convert("video_only_no_audio.mp4")
        assertEquals(ConverterResult.Failure(FailureReason.NoAudioTrack), result)
    }

    @Test
    fun sixChannelFailsWithUnsupportedChannelLayout() {
        val (result, _) = convert("sine_6ch_aac_3s.mp4")
        assertEquals(ConverterResult.Failure(FailureReason.UnsupportedChannelLayout), result)
    }

    @Test
    fun cancellationStopsPromptlyBeforeCompletion() {
        // Baseline: a full conversion of the same fixture, to compare output sizes against.
        val (fullResult, fullMp3) = convert("sine_stereo_aac_3s.mp4")
        assertEquals(ConverterResult.Success, fullResult)

        val ticks = AtomicInteger(0)
        val progress = mutableListOf<Int>()
        // Cancel as soon as the first progress arrives, so conversion stops mid-file.
        val (result, partialMp3) = convert(
            "sine_stereo_aac_3s.mp4",
            isCancelled = { ticks.get() > 0 },
            onProgress = {
                progress.add(it)
                ticks.incrementAndGet()
            },
        )
        // Per the contract, the converter returns Success on the cancel path (the service
        // aborts the sink and marks the job cancelled); it must not have run to 100%...
        assertEquals(ConverterResult.Success, result)
        assertFalse("should not have completed", progress.contains(100))
        // ...and it must have produced substantially less output than a full conversion.
        assertTrue(
            "cancelled output (${partialMp3.size}) should be well below full (${fullMp3.size})",
            partialMp3.size < fullMp3.size / 2,
        )
    }
}
